on:
  push:
    tags-ignore:
      - '**'
    branches:
      - '**'
name: Flutter integration test
jobs:
  android:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30]
        target: [default, google_apis]
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.3.8'
          channel: 'stable'

      # Run integration test
      - name: Run Flutter tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          target: ${{ matrix.target }}
          api-level: ${{ matrix.api-level }}
          arch: x86
          profile: Pixel 4 API 30
          script: flutter test integration_test/increment_success_test.dart
#  android:
#    runs-on: macos-13
#    strategy:
#      matrix:
#        api-level: [30]
#        target: [default]
#          # you can add more API level if you want to run your tests on different API
#      fail-fast: true
#    steps:
#      - uses: actions/checkout@v2
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: stable
#          # instead of "channel: stable", you could be more precise by specifying the exact version of Flutter you're using:
#          # flutter-version: '<FLUTTER_VERSION>'
#      - name: Run Flutter Integration_test
#        run: flutter pub get
#      - name: Run integration tests
#        # more info on https://github.com/ReactiveCircus/android-emulator-runner
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          target: ${{ matrix.target }}
#          api-level: ${{ matrix.api-level }}
#          arch: x86
#          profile: Pixel 4 API 30
#          script: flutter test integration_test/increment_success_test.dart